name: Test reusable SBOM workflow

on:
  push:
    branches:
      - test-reusable-sbom-workflow

jobs:
  sbom-scan:
    permissions:
      contents: read
      security-events: write

    uses: TaniaGithub0401/github-workflows/.github/workflows/sbom-vulnerability-scan.yml@add-reusable-sbom-vulnerability-workflow
    with:
      requirements: requirements-test.txt
      fail-build: false