name: Test reusable SBOM workflow

on:
  push:
    branches:
      - test-reusable-sbom-workflow

jobs:
  sbom-scan:
    uses: TaniaGithub0401/github-workflows/.github/workflows/sbom-vulnerability-scan.yml@add-reusable-sbom-vulnerability-workflow
    with:
      dockerfile: docker/actinia-core-alpine/Dockerfile
      image: localbuild/testimage:latest
      fail-build: false
    